import { createActionTypes } from "@src/utility"

export const JOBS_ACTION_TYPES = createActionTypes("jobs", [
  "GET_ALL_JOBS_REQUEST",
  "GET_ALL_JOBS_SUCCESS",
  "GET_ALL_JOBS_FAIL",
  "GET_SPECIFIC_JOB_REQUEST",
  "GET_SPECIFIC_JOB_SUCCESS",
  "GET_SPECIFIC_JOB_FAIL",
  "CLEAR_SPECIFIC_JOB",
  "APPLY_FOR_JOB_REQUEST",
  "APPLY_FOR_JOB_SUCCESS",
  "APPLY_FOR_JOB_FAIL",
  "SAVE_JOB_AS_DRAFT_REQUEST",
  "SAVE_JOB_AS_DRAFT_SUCCESS",
  "SAVE_JOB_AS_DRAFT_FAIL",
  "GET_ALL_APPLIED_JOBS_REQUEST",
  "GET_ALL_APPLIED_JOBS_SUCCESS",
  "GET_ALL_APPLIED_JOBS_FAIL",
  "GET_SPECIFIC_APPLIED_JOB_REQUEST",
  "GET_SPECIFIC_APPLIED_JOB_SUCCESS",
  "GET_SPECIFIC_APPLIED_JOB_FAIL",
  "CLEAR_SPECIFIC_APPLIED_JOB",
  "RESET_APPLY_FOR_JOB",
  "CREATE_JOB_REQUEST",
  "CREATE_JOB_SUCCESS",
  "CREATE_JOB_FAIL",
  "RESET_CREATE_JOB",
  "RESET_GET_ALL_JOBS"
])

// get all applied jobs request
